# Generated by Django 5.2 on 2026-06-01 10:58

from django.conf import settings
from django.db import migrations, models


def _variant_codes() -> list[str]:
    default = settings.LANGUAGE_CODE.lower()
    return [code for code, _ in settings.LANGUAGES if code.lower() != default]


def list_to_dict(apps, schema_editor) -> None:
    codes = _variant_codes()
    for model_name in ("Commodity", "CommodityGroup"):
        model = apps.get_model("db", model_name)
        for obj in model.objects.all():
            if not isinstance(obj.name_variants, list):
                continue
            obj.name_variants = {code: value for code, value in zip(codes, obj.name_variants) if value}
            obj.save(update_fields=["name_variants"])


def dict_to_list(apps, schema_editor) -> None:
    codes = _variant_codes()
    for model_name in ("Commodity", "CommodityGroup"):
        model = apps.get_model("db", model_name)
        for obj in model.objects.all():
            if not isinstance(obj.name_variants, dict):
                continue
            obj.name_variants = [obj.name_variants.get(code, "") for code in codes]
            obj.save(update_fields=["name_variants"])


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0003_register_periodic_tasks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commodity",
            name="name_variants",
            field=models.JSONField(blank=True, default=dict, help_text="Name translations keyed by language code"),
        ),
        migrations.AlterField(
            model_name="commoditygroup",
            name="name_variants",
            field=models.JSONField(blank=True, default=dict, help_text="Name translations keyed by language code"),
        ),
        migrations.RunPython(list_to_dict, dict_to_list),
    ]
