# Generated by Django 5.2.15 on 2026-09-29 19:36

import uuid
import whimo.db.models.whatsapp
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0004_name_variants_to_dict"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Timestamp when this record was created."),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Timestamp when this record was last updated."),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=False, help_text="Send phone verification codes through WhatsApp instead of SMS."
                    ),
                ),
                (
                    "api_version",
                    models.CharField(default="v21.0", help_text="Graph API version, for example v21.0.", max_length=16),
                ),
                (
                    "phone_number_id",
                    models.CharField(
                        blank=True,
                        help_text="Phone number ID of the sender, from WhatsApp Manager > API Setup.",
                        max_length=64,
                    ),
                ),
                (
                    "access_token",
                    models.TextField(
                        blank=True,
                        help_text="Permanent access token of a system user with the whatsapp_business_messaging permission.",
                    ),
                ),
                (
                    "template_name",
                    models.CharField(
                        blank=True,
                        help_text='Name of an approved message template of the "Authentication" category, with a copy-code button.',
                        max_length=512,
                    ),
                ),
                (
                    "template_languages",
                    models.JSONField(
                        blank=True,
                        default=whimo.db.models.whatsapp.default_template_languages,
                        help_text='Template language to use for each app language, for example {"en-us": "en_US", "fr-fr": "fr", "es-es": "es"}.',
                    ),
                ),
                (
                    "test_phone_number",
                    models.CharField(
                        blank=True,
                        help_text='Number that receives the code sent by "Send test message", with country code.',
                        max_length=32,
                    ),
                ),
                ("last_test_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("last_test_status", models.TextField(blank=True, editable=False)),
            ],
            options={
                "verbose_name": "WhatsApp settings",
                "verbose_name_plural": "WhatsApp settings",
            },
        ),
    ]
