# Generated by Django 5.2 on 2025-05-27 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0004_alter_transaction_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commodity",
            name="group",
            field=models.ForeignKey(
                help_text="Commodity group",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="commodities",
                to="db.commoditygroup",
            ),
        ),
    ]
