# Generated by Django 5.2 on 2025-05-27 15:23

import django.db.models.deletion
import simple_history.models
import uuid
import whimo.db.enums.transactions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0005_alter_commodity_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltransaction",
            name="traceability",
            field=models.CharField(
                choices=[
                    ("full", "FULL"),
                    ("conditional", "CONDITIONAL"),
                    ("partial", "PARTIAL"),
                    ("incomplete", "INCOMPLETE"),
                ],
                default=whimo.db.enums.transactions.TransactionTraceability["INCOMPLETE"],
                help_text="Traceability status of the transaction",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="traceability",
            field=models.CharField(
                choices=[
                    ("full", "FULL"),
                    ("conditional", "CONDITIONAL"),
                    ("partial", "PARTIAL"),
                    ("incomplete", "INCOMPLETE"),
                ],
                default=whimo.db.enums.transactions.TransactionTraceability["INCOMPLETE"],
                help_text="Traceability status of the transaction",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Balance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Timestamp when this record was created."),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Timestamp when this record was last updated."),
                ),
                ("volume", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                (
                    "commodity",
                    models.ForeignKey(
                        blank=True,
                        help_text="Balance commodity",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="db.commodity",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Balance user",
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Balance",
                "verbose_name_plural": "Balances",
                "db_table": "balances",
            },
        ),
        migrations.CreateModel(
            name="HistoricalBalance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                    ),
                ),
                ("volume", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "commodity",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Balance commodity",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="db.commodity",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Balance user",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Balance",
                "verbose_name_plural": "historical Balances",
                "db_table": "balances_history",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
