# Generated by Django 5.2 on 2025-05-28 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0008_create_balances"),
    ]

    operations = [
        migrations.AlterField(
            model_name="balance",
            name="commodity",
            field=models.ForeignKey(
                default=None,
                help_text="Balance commodity",
                on_delete=django.db.models.deletion.PROTECT,
                to="db.commodity",
            ),
            preserve_default=False,
        ),
    ]
