# Generated by Django 5.2 on 2025-05-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0009_alter_balance_commodity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaltransaction",
            name="traceability",
            field=models.CharField(
                blank=True,
                choices=[
                    ("full", "FULL"),
                    ("conditional", "CONDITIONAL"),
                    ("partial", "PARTIAL"),
                    ("incomplete", "INCOMPLETE"),
                ],
                help_text="Traceability status of the transaction",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="traceability",
            field=models.CharField(
                blank=True,
                choices=[
                    ("full", "FULL"),
                    ("conditional", "CONDITIONAL"),
                    ("partial", "PARTIAL"),
                    ("incomplete", "INCOMPLETE"),
                ],
                help_text="Traceability status of the transaction",
                max_length=20,
                null=True,
            ),
        ),
    ]
