# Generated by Django 5.2 on 2025-06-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0011_historicaltransaction_is_buying_from_farmer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltransaction",
            name="is_automatic",
            field=models.BooleanField(default=False, help_text="Whether this transaction was created automatically"),
        ),
        migrations.AddField(
            model_name="transaction",
            name="is_automatic",
            field=models.BooleanField(default=False, help_text="Whether this transaction was created automatically"),
        ),
    ]
