# Generated by Django 5.2 on 2025-06-17 15:18

import django.db.models.deletion
import simple_history.models
import uuid
import whimo.common.encoders
import whimo.db.enums.notifications
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0015_expire_transactions_task"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        encoder=whimo.common.encoders.PrettyJSONEncoder,
                        help_text="Notification data",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "PENDING"), ("read", "READ")],
                        default=whimo.db.enums.notifications.NotificationStatus["PENDING"],
                        help_text="Status of the notification",
                        max_length=20,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("incoming_transaction", "INCOMING_TRANSACTION"),
                            ("missing_geodata", "MISSING_GEODATA"),
                        ],
                        help_text="Type of notification",
                        max_length=20,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="User who created this notification",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="User who received this notification",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Notification",
                "verbose_name_plural": "historical Notifications",
                "db_table": "notifications_history",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Timestamp when this record was created."),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Timestamp when this record was last updated."),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        encoder=whimo.common.encoders.PrettyJSONEncoder,
                        help_text="Notification data",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "PENDING"), ("read", "READ")],
                        default=whimo.db.enums.notifications.NotificationStatus["PENDING"],
                        help_text="Status of the notification",
                        max_length=20,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("incoming_transaction", "INCOMING_TRANSACTION"),
                            ("missing_geodata", "MISSING_GEODATA"),
                        ],
                        help_text="Type of notification",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this notification",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        help_text="User who received this notification",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="received_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notifications",
                "ordering": ("created_at",),
            },
        ),
    ]
