# Generated by Django 5.2 on 2025-06-18 09:39

import whimo.db.enums.notifications
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0016_historicalnotification_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalnotification",
            name="status",
            field=models.CharField(
                choices=[("pending", "PENDING"), ("read", "READ")],
                default=whimo.db.enums.notifications.NotificationStatus["PENDING"],
                help_text="Status of the notification",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="historicalnotification",
            name="type",
            field=models.CharField(
                choices=[
                    ("transaction_pending", "TRANSACTION_PENDING"),
                    ("transaction_accepted", "TRANSACTION_ACCEPTED"),
                    ("transaction_rejected", "TRANSACTION_REJECTED"),
                    ("transaction_expired", "TRANSACTION_EXPIRED"),
                    ("geodata_missing", "GEODATA_MISSING"),
                ],
                help_text="Type of notification",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="status",
            field=models.CharField(
                choices=[("pending", "PENDING"), ("read", "READ")],
                default=whimo.db.enums.notifications.NotificationStatus["PENDING"],
                help_text="Status of the notification",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("transaction_pending", "TRANSACTION_PENDING"),
                    ("transaction_accepted", "TRANSACTION_ACCEPTED"),
                    ("transaction_rejected", "TRANSACTION_REJECTED"),
                    ("transaction_expired", "TRANSACTION_EXPIRED"),
                    ("geodata_missing", "GEODATA_MISSING"),
                ],
                help_text="Type of notification",
                max_length=20,
            ),
        ),
    ]
