# Generated by Django 5.2 on 2025-06-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0017_alter_historicalnotification_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalnotification",
            name="type",
            field=models.CharField(
                choices=[
                    ("transaction_pending", "TRANSACTION_PENDING"),
                    ("transaction_accepted", "TRANSACTION_ACCEPTED"),
                    ("transaction_rejected", "TRANSACTION_REJECTED"),
                    ("transaction_expired", "TRANSACTION_EXPIRED"),
                    ("geodata_missing", "GEODATA_MISSING"),
                    ("geodata_updated", "GEODATA_UPDATED"),
                ],
                help_text="Type of notification",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("transaction_pending", "TRANSACTION_PENDING"),
                    ("transaction_accepted", "TRANSACTION_ACCEPTED"),
                    ("transaction_rejected", "TRANSACTION_REJECTED"),
                    ("transaction_expired", "TRANSACTION_EXPIRED"),
                    ("geodata_missing", "GEODATA_MISSING"),
                    ("geodata_updated", "GEODATA_UPDATED"),
                ],
                help_text="Type of notification",
                max_length=20,
            ),
        ),
    ]
