# Generated by Django 5.2 on 2025-08-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0021_rename_latitude_historicaltransaction_farm_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltransaction",
            name="farm_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, help_text="Farm latitude coordinate", max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicaltransaction",
            name="farm_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, help_text="Farm longitude coordinate", max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="farm_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, help_text="Farm latitude coordinate", max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="farm_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, help_text="Farm longitude coordinate", max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicaltransaction",
            name="transaction_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, help_text="Transaction latitude coordinate", max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicaltransaction",
            name="transaction_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, help_text="Transaction longitude coordinate", max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, help_text="Transaction latitude coordinate", max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, help_text="Transaction longitude coordinate", max_digits=9, null=True
            ),
        ),
    ]
