# Generated by Django 5.2 on 2025-09-18 16:29

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0026_populate_commodity_name_variants"),
    ]

    operations = [
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Timestamp when this record was created."),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Timestamp when this record was last updated."),
                ),
                ("name", models.CharField(help_text="Name of the season", max_length=255)),
                ("description", models.TextField(blank=True, help_text="Description of the season", null=True)),
                ("start_date", models.DateField(blank=True, help_text="Start date of the season", null=True)),
                ("end_date", models.DateField(blank=True, help_text="End date of the season", null=True)),
            ],
            options={
                "verbose_name": "Season",
                "verbose_name_plural": "Seasons",
                "db_table": "seasons",
                "ordering": ("-start_date",),
            },
        ),
        migrations.CreateModel(
            name="HistoricalSeason",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                    ),
                ),
                ("name", models.CharField(help_text="Name of the season", max_length=255)),
                ("description", models.TextField(blank=True, help_text="Description of the season", null=True)),
                ("start_date", models.DateField(blank=True, help_text="Start date of the season", null=True)),
                ("end_date", models.DateField(blank=True, help_text="End date of the season", null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Season",
                "verbose_name_plural": "historical Seasons",
                "db_table": "seasons_history",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalSeasonCommodity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "commodity",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Commodity",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="db.commodity",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Season",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="db.season",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Season Commodity",
                "verbose_name_plural": "historical Season Commodities",
                "db_table": "season_commodities_history",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name="historicaltransaction",
            name="season",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Season this transaction belongs to",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="db.season",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="season",
            field=models.ForeignKey(
                blank=True,
                help_text="Season this transaction belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="db.season",
            ),
        ),
        migrations.CreateModel(
            name="SeasonCommodity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Timestamp when this record was created."),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Timestamp when this record was last updated."),
                ),
                (
                    "commodity",
                    models.ForeignKey(
                        help_text="Commodity",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="season_commodities",
                        to="db.commodity",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        help_text="Season",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="season_commodities",
                        to="db.season",
                    ),
                ),
            ],
            options={
                "verbose_name": "Season Commodity",
                "verbose_name_plural": "Season Commodities",
                "db_table": "season_commodities",
                "ordering": ("season", "commodity"),
                "unique_together": {("season", "commodity")},
            },
        ),
        migrations.AddField(
            model_name="season",
            name="commodities",
            field=models.ManyToManyField(
                help_text="Commodities participating in this season",
                related_name="seasons",
                through="db.SeasonCommodity",
                to="db.commodity",
            ),
        ),
    ]
