"""Strings the apps ship, and the rules an uploaded translation file must follow.

catalog/<code>.json holds the strings built into the apps for one language (generated by
scripts/export_strings.py). English is the template: its keys are the only ones a file may
contain, and a translation must keep the placeholders of the English text.

A translation file has one section per platform. Web strings are grouped by namespace:

    {"web": {"common": {"email": "..."}}, "android": {"email": "..."}, "ios": {...}, "api": {...}}
"""

import json
import re
from collections import Counter
from collections.abc import Iterator
from dataclasses import dataclass, field
from functools import cache
from pathlib import Path
from typing import Any

from django.utils.translation import gettext as _

CATALOG_DIR = Path(__file__).resolve().parent / "catalog"
TEMPLATE_CODE = "en"

PLATFORMS = ("web", "android", "ios", "api")
NESTED_PLATFORMS = ("web",)

# printf (%s, %1$s, %@, %d, %(name)s), i18next ({{count}}), Trans tags (<0>, <btn>, </btn>)
PLACEHOLDER = re.compile(r"%(?:\(\w+\))?(?:\d+\$)?[-+#0]*\d*(?:\.\d+)?[sdifuxX@]|\{\{\s*[\w.]+\s*\}\}|</?\w+>")

Section = dict[str, Any]
Pack = dict[str, Section]


@cache
def shipped(code: str) -> Pack:
    """Strings the apps ship for a language, or an empty pack."""
    path = CATALOG_DIR / f"{code}.json"
    if not path.exists():
        return {}
    return json.loads(path.read_text(encoding="utf-8"))


def template() -> Pack:
    return shipped(TEMPLATE_CODE)


def iter_strings(pack: Pack, platform: str) -> Iterator[tuple[tuple[str, ...], Any]]:
    """(key path, value) of every string of a platform: (namespace, key) for web, (key,) otherwise."""
    section = pack.get(platform) or {}
    if platform in NESTED_PLATFORMS:
        for namespace, strings in section.items():
            if isinstance(strings, dict):
                for key, value in strings.items():
                    yield (namespace, key), value
            else:
                yield (namespace,), strings
    else:
        for key, value in section.items():
            yield (key,), value


def lookup(pack: Pack, platform: str, path: tuple[str, ...]) -> Any:
    value: Any = pack.get(platform) or {}
    for part in path:
        if not isinstance(value, dict):
            return None
        value = value.get(part)
    return value


def assign(pack: Pack, platform: str, path: tuple[str, ...], value: str) -> None:
    node = pack.setdefault(platform, {})
    for part in path[:-1]:
        node = node.setdefault(part, {})
    node[path[-1]] = value


def placeholders(text: str) -> Counter[str]:
    return Counter(match.replace(" ", "") for match in PLACEHOLDER.findall(text))


def count(pack: Pack) -> int:
    return sum(1 for platform in PLATFORMS for _ in iter_strings(pack, platform))


def template_size() -> int:
    return count(template())


def merged(code: str, overrides: Pack) -> Pack:
    """Every string of a language: shipped strings, then uploaded ones on top."""
    result: Pack = {}
    for source in (shipped(code), overrides):
        for platform in PLATFORMS:
            for path, value in iter_strings(source, platform):
                assign(result, platform, path, value)
    return result


def translated_count(code: str, overrides: Pack) -> int:
    """Number of template strings the language has, shipped or uploaded."""
    pack = merged(code, overrides)
    return sum(
        1
        for platform in PLATFORMS
        for path, _english in iter_strings(template(), platform)
        if lookup(pack, platform, path)
    )


def download(code: str, overrides: Pack) -> Pack:
    """File an administrator downloads to edit a language: every template key, with the
    language's text where it has one and the English text elsewhere."""
    pack = merged(code, overrides)
    result: Pack = {}
    for platform in PLATFORMS:
        for path, english in iter_strings(template(), platform):
            assign(result, platform, path, lookup(pack, platform, path) or english)
    return result


@dataclass
class UploadResult:
    translations: Pack = field(default_factory=dict)
    errors: list[str] = field(default_factory=list)
    unchanged: int = 0

    @property
    def is_valid(self) -> bool:
        return not self.errors

    @property
    def stored(self) -> int:
        return count(self.translations)


def parse_upload(code: str, content: bytes | str, previous: Pack | None = None) -> UploadResult:
    """Check an uploaded file and keep only what the apps don't already show.

    A string equal to the text the apps already show is dropped: the language's shipped text,
    or the English text where the language has none. Uploading the file downloaded for a
    language, with a few strings changed, therefore stores only those strings. Strings uploaded
    before and missing from the file are kept (`previous`).
    """
    result = UploadResult()
    data = _load(content, result)
    if data is None:
        return result

    for platform, path in _paths(previous or {}):
        assign(result.translations, platform, path, lookup(previous or {}, platform, path))

    for platform in PLATFORMS:
        if platform in data and not isinstance(data[platform], dict):
            result.errors.append(_("Section %s must be a JSON object.") % platform)
            continue
        for path, value in iter_strings(data, platform):
            _add_string(code, platform, path, value, result)

    if not result.is_valid:
        result.translations = {}
    return result


def _load(content: bytes | str, result: UploadResult) -> dict | None:
    try:
        data = json.loads(content)
    except (UnicodeDecodeError, ValueError) as exc:
        result.errors.append(_("The file is not valid JSON: %s") % exc)
        return None
    if not isinstance(data, dict):
        result.errors.append(_("The file must contain a JSON object with one section per platform."))
        return None

    unknown_sections = sorted(set(data) - set(PLATFORMS) - {"language"})
    if unknown_sections:
        result.errors.append(
            _("Unknown sections: %(sections)s. Expected: %(expected)s.")
            % {"sections": ", ".join(unknown_sections), "expected": ", ".join(PLATFORMS)}
        )
    return data


def _add_string(code: str, platform: str, path: tuple[str, ...], value: Any, result: UploadResult) -> None:
    name = f"{platform}: {'.'.join(path)}"
    english = lookup(template(), platform, path)
    if not isinstance(english, str):
        result.errors.append(_("%s: unknown key.") % name)
    elif not isinstance(value, str):
        result.errors.append(_("%s: the value must be text.") % name)
    elif not value.strip():
        return
    elif placeholders(value) != placeholders(english):
        result.errors.append(
            _("%(name)s: keep the placeholders of the English text (%(expected)s).")
            % {"name": name, "expected": " ".join(sorted(placeholders(english).elements())) or "-"}
        )
    elif value == _shown(code, platform, path, english):
        result.unchanged += 1
        _remove(result.translations, platform, path)
    else:
        assign(result.translations, platform, path, value)


def _shown(code: str, platform: str, path: tuple[str, ...], english: str) -> str:
    """Text the apps show for a string without any upload."""
    shown = lookup(shipped(code), platform, path)
    return shown if isinstance(shown, str) else english


def _paths(pack: Pack) -> Iterator[tuple[str, tuple[str, ...]]]:
    for platform in PLATFORMS:
        for path, _value in iter_strings(pack, platform):
            yield platform, path


def _remove(pack: Pack, platform: str, path: tuple[str, ...]) -> None:
    nodes = [pack.get(platform)]
    for part in path[:-1]:
        node = nodes[-1]
        nodes.append(node.get(part) if isinstance(node, dict) else None)
    last = nodes[-1]
    if isinstance(last, dict):
        last.pop(path[-1], None)
    # Drop the sections left empty.
    for depth in range(len(path) - 1, 0, -1):
        parent, child = nodes[depth - 1], nodes[depth]
        if isinstance(parent, dict) and child == {}:
            parent.pop(path[depth - 1], None)
    if pack.get(platform) == {}:
        pack.pop(platform)
