# Generated by Django 5.2.15 on 2026-09-30 10:51

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Timestamp when this record was created."),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Timestamp when this record was last updated."),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="ISO 639 code, for example hi. The apps use it to pick their strings.",
                        max_length=16,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-z]{2,3}(-[a-z0-9]{2,8})?$",
                                "Use a lowercase ISO 639 code, optionally with a region: hi, fr, pt-br.",
                            )
                        ],
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the language in that language, as shown in the language picker, for example हिन्दी.",
                        max_length=64,
                    ),
                ),
                (
                    "english_name",
                    models.CharField(
                        blank=True, help_text="Name of the language in English, for example Hindi.", max_length=64
                    ),
                ),
                (
                    "flag",
                    models.CharField(
                        blank=True,
                        help_text="Optional flag emoji shown next to the name, for example 🇮🇳.",
                        max_length=16,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True, help_text="Offer this language in the apps.")),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Language used when the user's language is not offered."
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(default=0, help_text="Order in the language picker, lowest first."),
                ),
                (
                    "translations",
                    models.JSONField(blank=True, default=dict, help_text="Uploaded strings, one section per platform."),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        editable=False,
                        help_text="Increases with each upload, so that the apps download the new strings.",
                    ),
                ),
            ],
            options={
                "verbose_name": "language",
                "verbose_name_plural": "languages",
                "ordering": ("position", "code"),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_default", True)),
                        fields=("is_default",),
                        name="languages_single_default",
                    )
                ],
            },
        ),
    ]
